baseurl: "http://www.thisguy.codes"
languageCodexr: "en-us"
title: "ThisGuy"
theme: "hyde"
MetaDataFormat: "yaml"
params:
    themeColor: "theme-base-0d"
    description: >
        I like code, fault toleance, metrics, monitoring, and not waking up at
        2am.
